---
- name: BNAS 02 module
  hosts: all
  tasks:

  - name: Test reachability to Ansible host
    ios_ping:
      dest: 10.10.10.254

  - name: Gather facts from device
    ios_facts:
      gather_subset:
        - "!config"
    register: ios_result

  - name: Print gathered facts
    #debug: msg="{{ ios_result }}"
    debug: msg="Serial number is {{ ios_result.ansible_facts.ansible_net_serialnum }}"
  - debug: msg="Hostname is {{ ios_result.ansible_facts.ansible_net_hostname }}"
  - debug: msg="IOS version is {{ ios_result.ansible_facts.ansible_net_version }}"

  - name: Play with NAPALM facts
    napalm_get_facts:
      username: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      dev_os: "{{ansible_network_os}}"
      hostname: "{{ansible_host}}"
      timeout: 60
      filter:
        - facts
        - interfaces_ip
    register: napalm_result

  - name: Print NAPALM gathered facts
    debug: msg="{{ napalm_result.ansible_facts.napalm_uptime }}"
  - debug: msg="{{ napalm_result.ansible_facts.napalm_interfaces_ip }}"
